/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false`
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		ASSETS: Fetcher;
		SESSIONS: KVNamespace;
		AUTH_SECRET_KEY: string;
		STRAVA_CLIENT_ID: string;
		STRAVA_CLIENT_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
